routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a department which
| contains the "web" middleware department. Now create something great!
|
*/

 Route::get('/', function () {
     return view('auth.login');
 });

 Route::get('home', function () {
     return view('welcome');
 });


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

Route::middleware('auth')->group(function (){
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::group(['middleware' => ['auth', 'can:admin']], function () {
        Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
            Route::resource('attendance_header', 'AttendanceHeaderController', ['except' => ['show', 'edit', 'delete', 'update']]);
            Route::get('attendance_header/{user_id}/{year_month}', 'AttendanceHeaderController@show')->name('attendance_header.show');
            Route::post('attendance_header/update', 'AttendanceHeaderController@update')->name('attendance_header.update');
            Route::get('attendance_header/delete/{user_id}/{year_month}/{work_date}', 'AttendanceHeaderController@destroy')->name('attendance_header.delete');
            Route::get('attendance_header/ajax_get_attendance_info', 'AttendanceHeaderController@ajaxGetAttendanceInfo')->name('attendance_header.ajax_get_attendance_info');
            Route::get('attendance_header/confirm', 'AttendanceHeaderController@confirm')->name('attendance_header.confirm');
            Route::get('attendance_header/export', 'AttendanceHeaderController@export')->name('attendance_header.export');

            Route::resource('department', 'DepartmentController', ['except' => ['show', 'edit', 'create', 'update', 'delete']]);

            Route::post('department/update/{department}', 'DepartmentController@update')->name('department.update');
            Route::get('department/delete/{department}', 'DepartmentController@destroy')->name('department.delete');

            Route::get('department/ajax_get_department_info', 'DepartmentController@ajaxGetDepartmentInfo')->name('department.ajax_get_department_info');


            Route::get('users', 'UsersController@index')->name('users.index');
            Route::get('users/ajax_get_user_info', 'UsersController@ajaxGetUserInfo')->name('users.ajax_get_user_info');
            Route::post('users/update', 'UsersController@update')->name('users.update');
            Route::post('users/destroy', 'UsersController@destroy')->name('users.destroy');

            Route::get('settings', 'SettingsController@edit')->name('settings.edit');
            Route::post('settings/update', 'SettingsController@update')->name('settings.update');
        });
    });

        Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {
            Route::group(['middleware' => ['loginUserCheck']], function () {
                Route::get('attendance_header/{user_id}/{year_month}', 'AttendanceHeaderController@show')->name('attendance_header.show');
                Route::post('attendance_header/update', 'AttendanceHeaderController@update')->name('attendance_header.update');
                Route::get('attendance_header/delete/{user_id}/{year_month}/{work_date}', 'AttendanceHeaderController@destroy')->name('attendance_header.delete');
            });

            Route::get('attendance_header/ajax_get_attendance_info', 'AttendanceHeaderController@ajaxGetAttendanceInfo')->name('attendance_header.ajax_get_attendance_info');

        });
});

app/Models/AttendanceHeader.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\AuthorObservable;

class AttendanceHeader extends Model
{
    use AuthorObservable;

    CONST FRACTION_1 = 1;
    CONST FRACTION_15 = 15;
    CONST FRACTION_30 = 30;

    //課題2 確定処理のフラグを定数宣言
    CONST IS_CONFIRMED = 1;
    CONST IS_NOT_CONFIRMED = 0;

    protected $table = 'attendance_header';

    protected $fillable = [
        'user_id',
        'year_month',
        'working_days',
        'scheduled_working_hours',
        'overtime_hours',
        'working_hours',
        'confirm_flag',
    ];

    public function attendancDailies() {
        return $this->hasMany('App\Models\AttendanceDaily', 'attendance_header_id');
    }

    public function user() {
        return $this->belongsTo('App\Models\User');
    }
}

app/Http/Controllers/Admin/AttendanceHeaderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Breaktime as AppBreaktime;
use App\Exports\UsersExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\AttendanceRequest;
use App\Http\Requests\AttendanceConfirmRequest;
use App\Http\Requests\BreaktimeRequest;
use App\Http\Resources\AttendanceDailyResource;
use App\Models\AttendanceDaily;
use App\Models\AttendanceHeader;
use App\Models\Company;
use App\Models\User;
use App\Models\Breaktime;
use App\Models\Department;
use App\Models\DepartmentMember;
use App\Services\AttendanceService;
use App\Services\GetDateService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Facades\Excel;

class AttendanceHeaderController extends Controller
{
    public function index(Request $request) {

        //Servicesクラスのインスタンスを作成
        $getDateService = new GetDateService();

        //変数dateに、Y-mの形でフォーマットされた月初の値を代入（2020-06）
        $date = $getDateService->createYearMonthFormat($request->year_month);

        //変数dateForSearchにY-m-dの形でフォーマットされた値を代入（2020-06-01）
        $dateForSearch = $date->format('Y-m-d');

        //変数queryにUserモデルからid昇順にソートした値を代入
        $query = User::orderBy('users.id');

        //変数usersにUserモデルで定義されたテーブル結合する関数を実行
        $users = $query->ledftJoinAttendanceHeader($dateForSearch);

        //テーブルを結合したデータ$usersと2020-06にフォーマットされた$dateをviewファイルと共にreturnする
        return view('admin.attendance_header.index')->with([
            'users' => $users,
            'date' => $date->format('Y-m'),
        ]);
    }

    public function show($user_id, $yearMonth) {

        $getDateService = new GetDateService();

        $date = $getDateService->createYearMonthFormat($yearMonth);

        $attendance = AttendanceHeader::firstOrNew(['user_id' => $user_id, 'year_month' => $date]);

        $atendanceDaily = AttendanceDaily::monthOfDailys($attendance->id);

        $daysOfMonth = $getDateService->getDaysOfMonth($date->copy());

        $company = Company::company();

        return view('admin.attendance_header.show')->with([
            'attendance' => $attendance,
            'atendanceDaily' => $atendanceDaily,
            'daysOfMonth' => $daysOfMonth,
            'date' => $date->format('Y-m'),
            'company' => $company,
        ]);
    }

    public function update(AttendanceRequest $request) {

        $attendanceService = new AttendanceService();
        $getDateService = new GetDateService();
        $date = $getDateService->createYearMonthFormat($request->year_month);

        try {
            DB::transaction(function () use ($request, $attendanceService, $date) {

                // 抽出①を実行
                $attendanceHeader = AttendanceHeader::firstOrCreate(['user_id' => $request->user_id, 'year_month' => $date]);

                // 労働時間計算処理(日)
                $requestParams = $request->validated();
                $updateDailyParams = $attendanceService->getUpdateDailyParams($requestParams);

                // 更新処理①を実行
                $attendanceDaily = AttendanceDaily::firstOrNew(['attendance_header_id' => $attendanceHeader->id, 'work_date' => $request->work_date]);
                $attendanceDaily->fill($updateDailyParams)->saveOrfail();

                // 課題4 休憩時間の削除処理
                Breaktime::where('attendance_daily_id', $attendanceDaily->id)->delete();
                // 課題4 休憩時間の登録処理
                $dailyBreakTimeParams = $requestParams['break_times'];
                $attendanceService->insertDailyBreakTime($dailyBreakTimeParams, $attendanceDaily->id);

                // 労働時間計算処理(月)
                $updateMonthParams = $attendanceService->getUpdateMonthParams($attendanceHeader->id);

                // 更新処理②を実行
                $attendanceHeader->fill($updateMonthParams)->saveOrFail();

            });
        } catch (\Exception $e) {
            report($e);
            session()->flash('flash_message', '更新が失敗しました');
        }

        return redirect(route('admin.attendance_header.show', ['user_id' => $request->user_id, 'year_month' => $date]));
    }

    public function destroy($user_id, $year_month, $work_date) {
        $attendanceService = new AttendanceService();

        // 抽出①を実行
        $getDateService = new GetDateService();
        $date = $getDateService->createYearMonthFormat($year_month);
        $attendanceHeader = AttendanceHeader::firstOrCreate(['user_id' => $user_id, 'year_month' => $date]);

        // 更新処理④
        Attendancedaily::where(['attendance_header_id' => $attendanceHeader->id, 'work_date' => $work_date])->delete();

        // 労働時間計算処理(月)
        $updateMonthParams = $attendanceService->getUpdateMonthParams($attendanceHeader->id);

        // 更新処理②を実行
        $attendanceHeader->fill($updateMonthParams)->saveOrFail();

        return redirect(route('admin.attendance_header.show', ['user_id' => $user_id, 'year_month' => $date]));
    }


    public function ajaxGetAttendanceInfo(Request $request) {
        $attendanceDaily = AttendanceDaily::findOrNew($request->id);
        return AttendanceDailyResource::make($attendanceDaily);
    }

    //課題2 確定処理の追加
    public function confirm(AttendanceConfirmRequest $request) {
        //AttendanceServicesクラスのインスタンスを作成
        $attendanceService = new AttendanceService();

        //抽出①を実行
        //GetDataServiceクラスのインスタンスを作成
        $getDataService = new GetDateService();
        $date = $getDataService->createYearMonthFormat($request->year_month);
        $attendanceHeader = AttendanceHeader::firstOrCreate(['user_id' => $request->user_id, 'year_month' => $date]);

        //変数confirmParamsに、対象userのconfirmパラメータを作成する
        $confirmParams = $attendanceService->createConfirmParams($attendanceHeader);

        DB::transaction(function() use ($attendanceHeader, $confirmParams) {
            $attendanceHeader->fill($confirmParams)->saveOrFail();
        });

         return redirect(route('admin.attendance_header.show',
             ['user_id' => $request->user_id,
             'year_month' => $request->year_month]));

    }

    //課題5で追加
    public function export(Request $request) {
        $getDateService = new GetDateService();
        $date = $getDateService->createYearMonthFormat($request->year_month);
        $dateForSearch = $date->format('Y-m-d');

        //①残業基準時間を超える勤怠ヘッダを取得
        $basis_time =  $request->overtimes_basis_time;
        $attendanceHeaders = AttendanceHeader::where('year_month', $dateForSearch)
        ->where('overtime_hours', '>', $basis_time)
        ->get();
        $count = count($attendanceHeaders);

        //②勤怠ヘッダ(①)からユーザー及び部署名を取得
        $matchedDepartmentArray = [];
        for($i = 0; $i < $count; $i++) {
            $userId = $attendanceHeaders[$i]->user_id;
            $departmentArray = DepartmentMember::getDepartments($userId);
            $departmentName = $departmentArray[0]['name'];
            array_push($matchedDepartmentArray, $departmentName);
        }

        //③部署名(②)の重複をチェックし、部署あたりの数を取得
        $departmentCount = array_count_values($matchedDepartmentArray);
        $depCount = count($departmentCount);

        //④③を連想配列ではなく普通の配列に変換
        $index = 0;
        $departmentCountPlaneArray = [];

        foreach($departmentCount as $key => $value) {
            $index += 1;
            $departmentCountPlaneArray[$index-1][0] = $key;
            $departmentCountPlaneArray[$index-1][1] = $value;
        }

        //⑤UsersExportクラスに④に渡しインスタンスを生成
        $export = new UsersExport($departmentCountPlaneArray);
        return Excel::download($export, 'users.xlsx');
    }
}

app/Http/Controllers/User/AttendanceHeaderController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\AttendanceRequest;
use App\Http\Resources\AttendanceDailyResource;
use App\Models\AttendanceDaily;
use App\Models\AttendanceHeader;
use App\Models\Company;
use App\Models\Breaktime;
use App\Services\AttendanceService;
use App\Services\GetDateService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AttendanceHeaderController extends Controller
{
    public function show($user_id, $yearMonth) {

        $getDateService = new GetDateService();

        $date = $getDateService->createYearMonthFormat($yearMonth);

        $attendance = AttendanceHeader::firstOrNew(['user_id' => $user_id, 'year_month' => $date]);

        $atendanceDaily = AttendanceDaily::monthOfDailys($attendance->id);

        $daysOfMonth = $getDateService->getDaysOfMonth($date->copy());

        $company = Company::company();

        return view('user.attendance_header.show')->with([
            'attendance' => $attendance,
            'atendanceDaily' => $atendanceDaily,
            'daysOfMonth' => $daysOfMonth,
            'date' => $date->format('Y-m'),
            'company' => $company,
        ]);
    }

    public function update(AttendanceRequest $request) {

        $attendanceService = new AttendanceService();
        $getDateService = new GetDateService();
        $date = $getDateService->createYearMonthFormat($request->year_month);

        try {
            DB::transaction(function () use ($request, $attendanceService, $date) {
                // 抽出①を実行
                $attendanceHeader = AttendanceHeader::firstOrCreate(['user_id' => $request->user_id, 'year_month' => $date]);

                // 労働時間計算処理(日)
                $requestParams = $request->validated();
                $updateDailyParams = $attendanceService->getUpdateDailyParams($requestParams);

                // 更新処理①を実行
                $attendanceDaily = AttendanceDaily::firstOrNew(['attendance_header_id' => $attendanceHeader->id, 'work_date' => $request->work_date]);
                $attendanceDaily->fill($updateDailyParams)->saveOrfail();

                // 課題4 休憩時間の削除処理
                Breaktime::where('attendance_daily_id', $attendanceDaily->id)->delete();
                // 課題4 休憩時間の登録処理
                $dailyBreakTimeParams = $updateDailyParams['break_times'];
                $attendanceService->insertDailyBreakTime($dailyBreakTimeParams, $attendanceDaily->id);

                // 労働時間計算処理(月)
                $updateMonthParams = $attendanceService->getUpdateMonthParams($attendanceHeader->id);

                // 更新処理②を実行
                $attendanceHeader->fill($updateMonthParams)->saveOrFail();
            });
        } catch (\Exception $e) {
            session()->flash('flash_message', '更新が失敗しました');
        }

        return redirect(route('user.attendance_header.show', ['user_id' => $request->user_id, 'year_month' => $date]));
    }

    public function destroy($user_id, $year_month, $work_date) {
        $attendanceService = new AttendanceService();

        // 抽出①を実行
        $getDateService = new GetDateService();
        $date = $getDateService->createYearMonthFormat($year_month);
        $attendanceHeader = AttendanceHeader::firstOrCreate(['user_id' => $user_id, 'year_month' => $date]);

        // 更新処理④
        Attendancedaily::where(['attendance_header_id' => $attendanceHeader->id, 'work_date' => $work_date])->delete();

        // 労働時間計算処理(月)
        $updateMonthParams = $attendanceService->getUpdateMonthParams($attendanceHeader->id);

        // 更新処理②を実行
        $attendanceHeader->fill($updateMonthParams)->saveOrFail();

        return redirect(route('user.attendance_header.show', ['user_id' => $user_id, 'year_month' => $date]));
    }

    public function ajaxGetAttendanceInfo(Request $request) {
        $attendanceDaily = AttendanceDaily::findOrNew($request->id);
        return AttendanceDailyResource::make($attendanceDaily);
    }
}

resources/views/admin/attendance_header/index.blade.php
@extends('layouts.app')

@section('addCss')
@endsection

@section('content')
<div class="container">
    <div class="row pb-3">
        <div class="col-12">
            <form method="GET" action="{{ route('admin.attendance_header.index') }}">
                @csrf
                <input type="text" class="monthPick" id="year_month" name="year_month" value="{{ $date }}">
                <input type="submit" class="d-none" id="year_month_submit">
            </form>
        </div>
    </div>
    <table class="table table-bordered">
        <thead class="bg-info">
            <tr>
                <th width="30%">社員名</th>
                <th>勤務日数</th>
                <th>所定内労働時間</th>
                <th>残業時間</th>
                <th>総労働時間</th>
                <th width="10%"></th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users AS $user)
            <tr class="bg-white">
                <th class="text-center">{{ $user->last_name }}{{ $user->first_name }}</th>
                <th class="text-center">{{ AttendanceHelper::daysFormat($user->working_days) }}日</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($user->scheduled_working_hours) }}</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($user->overtime_hours) }}</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($user->working_hours) }}</th>
                <td class="text-center">
                    <a href="{{ route('admin.attendance_header.show', ['user_id' => $user->user_id, 'year_month' => $date]) }}" class="btn btn-info">詳細</a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="row d-flex justify-content-end mr-0">
        <div class="col-md-7 mt-1 pr-0 d-flex justify-content-end">
            <form method="GET" action="{{ route('admin.attendance_header.export') }}">
            @csrf
                残業基準時間：<input type="time" name="overtimes_basis_time">
                <input type="hidden" value={{ $date }} name="year_month">
                <input type="hidden" value={{ $users }} name="users">
                <button type="submit" class="btn btn-success text-nowrap btn-sm">出力</button>
            </form>
         </div>
    </div>
</div>

@endsection
@section('addJs')

@endsection

resources/views/admin/attendance_header/show.blade.php
@extends('layouts.app')

@section('addCss')
    <link rel="stylesheet" href="{{ asset('/css/admin/form.css') }}">
@endsection

@section('content')
    <div class="container company validation-url" id="attendance-info-url" data-url="{{ route('admin.attendance_header.ajax_get_attendance_info') }}" data-base_time_from="{{ $company->base_time_from }}" data-base_time_to="{{ $company->base_time_to }}">
        <div class="row pb-3 d-flex justify-content-between col-12">
            <form method="GET" action="{{ route('admin.attendance_header.index') }}">
                @csrf
                <input type="hidden" name="year_month" value="{{ $date }}">
                <button type="submit" class="d-none" id="year_month_submit"></button>
                <div class="col-12">
                    <div class="back-index click-text">戻る</div>
                </div>
            </form>
        </div>

        <div class="row pb-3">
            <div class="float-right">
                <form method="GET" action="{{ route('admin.attendance_header.confirm') }}">
                    @csrf
                    <input type="hidden" name="year_month" value="{{ $date }}">
                    <input type="hidden" name="user_id" value="{{ $attendance->user_id }}">
                    <button type="submit" class="btn btn-secondary px-5">{{ AttendanceHelper::isConfirmed($attendance->confirm_flag) }}</button>
                </form>
            </div>
        </div>


        <div class="row pb-3 d-flex">
            <div class="col-md-4 mt-3">
                <div data-action="{{ route('admin.attendance_header.show', ['user_id' => $attendance->user_id, 'year_month' => 'year_month']) }}" id="year_month_url">
                    <input type="text" class="monthPick" id="year_month" name="year_month" value="{{ $date }}">
                    <input type="submit" class="d-none" id="year_month_submit">
                </div>
            </div>

            <div class="col-md-4 justify-content-end mt-3">
                <div>
                    <h2>{{ $attendance->user->last_name }}{{ $attendance->user->first_name }}</h2>
                </div>
            </div>
        </div>

        @if ($attendance->confirm_flag == \App\Models\AttendanceHeader::IS_CONFIRMED)
            <div class="col-12 pr-0 pl-0">
                <div class="alert alert-danger">
                    確定済みのため操作することが出来ません。
                </div>
            </div>
        @endif

        <table class="table table-bordered {{ $attendance->confirm_flag == \App\Models\AttendanceHeader::IS_CONFIRMED ? 'none-events' : '' }}">
            <thead class="bg-info">
            <tr>
                <th>勤務日数</th>
                <th>所定内労働時間</th>
                <th>残業時間</th>
                <th>総労働時間</th>
            </tr>
            </thead>
            <tbody>
            <tr class="bg-white">
                <th class="text-center">{{ AttendanceHelper::daysFormat($attendance->working_days) }}日</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($attendance->scheduled_working_hours) }}</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($attendance->overtime_hours) }}</th>
                <th class="text-center">{{ AttendanceHelper::timeFormat($attendance->working_hours) }}</th>
            </tr>
            </tbody>
        </table>
        <table class="table table-bordered">
            <thead class="bg-info">
            <tr>
                <th>日付</th>
                <th></th>
                <th>区分</th>
                <th>勤務</th>
                <th>休憩時間</th>
                <th>所定内労働</th>
                <th>残業</th>
                <th>総労働時間</th>
            </tr>
            </thead>
            <tbody>
            @foreach($daysOfMonth as $day)
                <tr class="bg-white dateInfo">
                    <th class="text-right dialog date_info work_date click-text" data-date_info="{{ $date . '-' . $day['day'] . '(' . $day['dayOfWeek'] . ')' }}" data-work_date="{{ $day['work_date'] }}">{{ $day['day'] }}日</th>
                    <th class="text-center">{{ $day['dayOfWeek'] }}</th>
                    @if (count($atendanceDaily) > 0)
                        @if (isset($atendanceDaily[$day['work_date']]))
                            <th class="text-center attendance_class memo id"  data-id="{{ $atendanceDaily[$day['work_date']]['id'] }}">
                                {{ AttendanceHelper::attendanceClass($atendanceDaily[$day['work_date']]['attendance_class']) }}
                            </th>
                            <th class="text-center working_time leave_time">
                                {{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['working_time'])  }}
                                ~
                                {{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['leave_time']) }}
                            </th>
                            <th class="text-center break_time_from break_time_to">
{{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['break_times'])  }}
                            </th>
                            <th class="text-right scheduled_working_hours">
                                {{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['scheduled_working_hours']) }}
                            </th>
                            <th class="text-right overtime_hours">
                                {{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['overtime_hours']) }}
                            </th>
                            <th class="text-right working_hours">
                                {{ AttendanceHelper::timeFormat($atendanceDaily[$day['work_date']]['working_hours']) }}
                            </th>
                        @else
                            <th class="text-center"></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        @endif
                    @else
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    @endif
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div><!-- /.modal-header -->
                <form method="GET" action="{{ route('admin.attendance_header.update') }}" id="modal-form">
                    @csrf
                    <div class="modal-body">
                        <div class="row">
                            <div class="alert-danger d-none col-12">
                                <ul>

                                </ul>
                            </div>
                        </div>
                        <input type="hidden" name="user_id" value="{{ $attendance->user_id }}">
                        <input type="hidden" name="year_month" value="{{ $date }}">
                        <input type="hidden" name="work_date" value="" id="work_date">
                        <div class="form-group row">
                            <label for="attendance_class" class="col-md-4 col-form-label text-right">
                                区分
                            </label>
                            <div class="col-md-8">
                                <div class="form-inline">
                                    <select name="attendance_class" class="form-control" id="attendance_class">
                                        <option value="0">通常勤務</option>
                                        <option value="1">有給休暇</option>
                                        <option value="2">欠勤</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="working_time" class="col-md-4 col-form-label text-right">
                                出勤
                            </label>
                            <div class="col-md-8">
                                <div class="form-inline">
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <input id="working_time" size="8" type="time" name="working_time" class="form-control" value="{{ $company->base_time_from }}">
                                    </div>
                                    <div class="input-group mb-2 mr-sm-2  ml-sm-2 mb-sm-0">
                                        〜
                                    </div>
                                    <div class="input-group mb-2 ml-sm-2 mb-sm-0">
                                        <input id="leave_time" type="time" size="8" name="leave_time" class="form-control" value="{{ $company->base_time_to }}">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row" id="breaktime">
                            <label class="col-md-4 col-form-label text-right">
                                休憩
                            </label>
                            <div class="col-md-8 d-flex mt-2">
                                休憩時間を追加する
                                <div class="mb-2 ml-sm-2 mb-sm-0">
                                        <button type="button" class="btn btn-success rounded-circle p-0 mb-2" style="width:1.5rem;height:1.5rem;" id="plus">＋</button>
                                </div>
                            </div>
                            <div class="col-md-8 offset-md-4 mb-2 " id="breaktime_form" style="display: none;">
                                <div class="form-inline">
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <input id="break_time_from" size="8" type="time" name="" class="form-control" value="12:00">
                                    </div>
                                    <div class="input-group mb-2 mr-sm-2  ml-sm-2 mb-sm-0">
                                        〜
                                    </div>
                                    <div class="input-group mb-2 ml-sm-2 mb-sm-0">
                                        <input id="break_time_to" type="time" size="8" name="" class="form-control" value="13:00">
                                    </div>

                                </div>
                            </div>
                        </div>





                        <div class="form-group row">
                            <label for="memo" class="col-md-4 control-label col-form-label text-right">
                                メモ
                            </label>
                            <div class="col-md-8">
                                <textarea class="field-textarea" id="memo" class="form-control" name="memo"></textarea>
                            </div>
                        </div>

                    </div><!-- /.modal-body -->
                    <div class="modal-footer">
                        <a data-url="{{ route('admin.attendance_header.delete', ['user_id' => $attendance->user_id, 'year_month' => $date, 'work_date' => 'work_date']) }}" class="btn btn-secondary" id="delete-url">未入力に戻す</a>
                        <button type="button" class="btn btn-primary" id="attendance_submit">変更を保存</button>
                    </div><!-- /.modal-footer -->
            </div><!-- /.modal-content -->
            </form>
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
@endsection
@section('addJs')
    <script src="{{ asset('js/attendanceForm.js') }}"></script>
    <script src="{{ asset('js/addBreaktimeArea.js') }}"></script>
@endsection