routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a department which
| contains the "web" middleware department. Now create something great!
|
*/

 Route::get('/', function () {
     return view('auth.login');
 });

 Route::get('home', function () {
     return view('welcome');
 });


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

Route::middleware('auth')->group(function (){
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    Route::group(['middleware' => ['auth', 'can:admin']], function () {
        Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
            Route::resource('attendance_header', 'AttendanceHeaderController', ['except' => ['show', 'edit', 'delete', 'update']]);
            Route::get('attendance_header/{user_id}/{year_month}', 'AttendanceHeaderController@show')->name('attendance_header.show');
            Route::post('attendance_header/update', 'AttendanceHeaderController@update')->name('attendance_header.update');
            Route::get('attendance_header/delete/{user_id}/{year_month}/{work_date}', 'AttendanceHeaderController@destroy')->name('attendance_header.delete');
            Route::get('attendance_header/ajax_get_attendance_info', 'AttendanceHeaderController@ajaxGetAttendanceInfo')->name('attendance_header.ajax_get_attendance_info');
            Route::get('attendance_header/confirm', 'AttendanceHeaderController@confirm')->name('attendance_header.confirm');
            Route::get('attendance_header/export', 'AttendanceHeaderController@export')->name('attendance_header.export');

            Route::resource('department', 'DepartmentController', ['except' => ['show', 'edit', 'create', 'update', 'delete']]);

            Route::post('department/update/{department}', 'DepartmentController@update')->name('department.update');
            Route::get('department/delete/{department}', 'DepartmentController@destroy')->name('department.delete');

            Route::get('department/ajax_get_department_info', 'DepartmentController@ajaxGetDepartmentInfo')->name('department.ajax_get_department_info');


            Route::get('users', 'UsersController@index')->name('users.index');
            Route::get('users/ajax_get_user_info', 'UsersController@ajaxGetUserInfo')->name('users.ajax_get_user_info');
            Route::post('users/update', 'UsersController@update')->name('users.update');
            Route::post('users/destroy', 'UsersController@destroy')->name('users.destroy');

            Route::get('settings', 'SettingsController@edit')->name('settings.edit');
            Route::post('settings/update', 'SettingsController@update')->name('settings.update');
        });
    });

        Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function () {
            Route::group(['middleware' => ['loginUserCheck']], function () {
                Route::get('attendance_header/{user_id}/{year_month}', 'AttendanceHeaderController@show')->name('attendance_header.show');
                Route::post('attendance_header/update', 'AttendanceHeaderController@update')->name('attendance_header.update');
                Route::get('attendance_header/delete/{user_id}/{year_month}/{work_date}', 'AttendanceHeaderController@destroy')->name('attendance_header.delete');
            });

            Route::get('attendance_header/ajax_get_attendance_info', 'AttendanceHeaderController@ajaxGetAttendanceInfo')->name('attendance_header.ajax_get_attendance_info');

        });
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\AuthorObservable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Department extends Model
{
    use AuthorObservable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    public function getDepartmentSelectList(){
        return $this->select([
            'departments.id',
            'departments.name',
        ])
        ->get();
    }
}

app/Http/Controllers/Admin/DepartmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\DepartmentCreateValidationRequest;
use App\Http\Requests\DepartmentUpdateValidationRequest;
use App\Http\Resources\DepartmentResource;
use App\Models\Department;
use App\Models\DepartmentMember;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DepartmentController extends Controller
{
    public function index() {
        $departments = Department::all();

        return view('admin.department.index')->with([
            'departments' => $departments,
        ]);
    }

    public function store(DepartmentCreateValidationRequest $request) {
        $params = $request->validated();

        DB::transaction(function () use ($request, $params) {
            $department = Department::create($params);
        });

        session()->flash('flash_message', '登録が成功しました');

        return redirect(route('admin.department.index'));
    }

    public function update(DepartmentUpdateValidationRequest $request, $id) {
        $params = $request->validated();

        DB::transaction(function () use ($request, $params, $id) {
            $department = Department::findOrFail($id)->fill($params);

            $department->saveOrFail();
        });

        session()->flash('flash_message', '更新が成功しました');

        return redirect(route('admin.department.index'));
    }

    public function destroy($id) {

        DB::transaction(function () use ($id) {

            $department = Department::findOrFail($id);

            DepartmentMember::where('department_id', '=', $id)->delete();

            $department->delete();
        });

        session()->flash('flash_message', '削除が成功しました');

        return redirect(route('admin.department.index'));
    }

    public function ajaxGetDepartmentInfo(Request $request) {
        $department = Department::findOrNew($request->id);

        return DepartmentResource::make($department);
    }
}

resources/views/admin/department/index.blade.php
@extends('layouts.app')

@section('addCss')
@endsection

@section('content')
    <div class="container department-info-url" id="department-index" data-url="{{ route('admin.department.ajax_get_department_info') }}">

        <div class="row pb-5">
            <div class="col-12">
                <div class="create-route float-right">
                    <button class="btn btn-primary px-5 add-dialog" id="add-department" data-action="{{ route('admin.department.store') }}">部門追加</button>
                </div>
            </div>
        </div>

        <table class="table table-bordered" id="edit-department" data-action="{{ route('admin.department.update', ['department' => 'department_id']) }}">
            <thead class="bg-info">
            <tr>
                <th>部門名</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach ($departments AS $department)
                <tr class="bg-white">
                    <th class="text-center" ><span class="edit-department click-text" data-id="{{ $department->id }}">{{ $department->name }}</span></th>

                    <td class="text-center">
                        <a href="{{ route('admin.department.delete', ['department' => $department->id]) }}" class="btn btn-danger">削除</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="modal fade" tabindex="-1" id="form-modal" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div><!-- /.modal-header -->
                <form method="GET" id="modal-form">
                    <input type="hidden" name="_token" id="_token" value="{{ csrf_token() }}">
                    <div class="modal-body">
                        <div class="alert-danger d-none col-12">
                            <ul>

                            </ul>
                        </div>
                        <input type="hidden" name="id" value="" id="id">

                        <div class="form-group row">
                            <label for="name" class="col-md-4 control-label col-form-label text-right">
                                部門名
                            </label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" id="name">
                            </div>
                        </div>

                    </div><!-- /.modal-body -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" id="department-submit">保存</button>
                    </div><!-- /.modal-footer -->
            </div><!-- /.modal-content -->
            </form>
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection
@section('addJs')
    <script src="{{ asset('js/departmentForm.js') }}"></script>
@endsection